# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_mi_matrix <- function(data, bins_per_var, spline_order, n_threads) {
    .Call(`_clr_cpp_mi_matrix`, data, bins_per_var, spline_order, n_threads)
}

cpp_clr_calibrate <- function(mi, combine) {
    .Call(`_clr_cpp_clr_calibrate`, mi, combine)
}


cpp_openmp_info <- function() {
    .Call(`_clr_cpp_openmp_info`)
}

cpp_weights_at <- function(v, xmin, xmax, spline_order, num_bins) {
    .Call(`_clr_cpp_weights_at`, v, xmin, xmax, spline_order, num_bins)
}
